// export const data = [
//   {
//     id: 1,
//     name: "techbullion.com",
//     url: "www.techbullion.com",
//     img: wellness,
//     DA: 64,
//     DAPercentage: 4,
//     positive: false,
//     PA: 75,
//     traffic: 10.7,
//     spamScore: 4.0,
//     price: 90,
//     linkType: "Dofollow",
//   },
//   {
//     id: 2,
//     name: "wellnesspitch.com",
//     url: "www.wellnesspitch.com",
//     img: techbullion,
//     DA: 62,
//     DAPercentage: 5,
//     positive: true,
//     PA: 55,
//     traffic: 65.7,
//     spamScore: 1.0,
//     price: 65,
//     linkType: "Dofollow",
//   },
// ];
